### ISSUE TITLE
Feedback from Staff

### ISSUE THREAD

**Issue by laurenancona** [CityOfPhiladelphia/greenworks-dashboard#14]
- [x] Vision 2 – Can we add a link to the City’s AQI landing page where the caption currently says “Air Quality Index?” -- http://www.phila.gov/aqi/
- [x] Vision 3 – Y axis label on the left should be Degree Days
- [x] Vision 6 – Can we remove the “Low Carbon Commute” box/data, and instead add one more sentence in the caption that says “Low-carbon commuting in Philadelphia has increased  by more than 7,000 people in the past five years.”
  - [x] Below the source, would it be possible to add one more sentence letting folks know they can manipulate the chart? Maybe “Click mode types in the chart to see commuting patterns in Philadelphia.”
  - [x] Since we’re sticking with showing driving and carpooling, the title of this chart should change to Commuting in Philadelphia
- [x] Vision 7 – Could we reorganize the three datasets so that Landfill is at the bottom, Recycling in the middle, and Waste to Energy at the top?
- [x] Vision 8 -- Just wanted to confirm that PowerCorps numbers will be added (they should be in the most recent spreadsheet you received). 
  - [x] Also, could the label please read PowerCorpsPHL?

**Comment by laurenancona** [comment]
Closing this, but still need numbers for PowerCorps PHL - they were not included in latest update; emailed them.

**Comment by timwis** [comment]
killin it @laurenancona! looks great
